# Generated by Django 3.1 on 2023-06-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscapacitados', '0002_auto_20230531_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria'], 'verbose_name': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='condicionactividadeconomica',
            options={'ordering': ['estado_economico'], 'verbose_name': 'Condicion Actividad Economica'},
        ),
        migrations.AlterModelOptions(
            name='condicioneconomicapordiscapacidad',
            options={'ordering': ['tipo_discapacidad'], 'verbose_name': 'Condicion Economica por discapacidad'},
        ),
        migrations.AlterModelOptions(
            name='discapacitadoporgenero',
            options={'ordering': ['genero'], 'verbose_name': 'Discapacitado Por Genero'},
        ),
        migrations.AlterModelOptions(
            name='informaciongrafica',
            options={'ordering': ['titulo'], 'verbose_name': 'Información gráfica'},
        ),
        migrations.AlterModelOptions(
            name='participacionpordiscapacidad',
            options={'ordering': ['tipo_discapacidad'], 'verbose_name': 'Participacion Por Discapacidad'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['titulo_publicacion'], 'verbose_name': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='resumen',
            options={'ordering': ['sintesis'], 'verbose_name': 'Resumenes'},
        ),
        migrations.AlterModelOptions(
            name='tablas',
            options={'ordering': ['tipo'], 'verbose_name': 'Tablas'},
        ),
    ]
