# Generated by Django 3.1 on 2023-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscapacitados', '0003_auto_20230602_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='condicionactividadeconomica',
            options={'ordering': ['estado_economico'], 'verbose_name': 'Condicion Actividad Economica', 'verbose_name_plural': 'Condicion Actividad Economica'},
        ),
        migrations.AlterModelOptions(
            name='condicioneconomicapordiscapacidad',
            options={'ordering': ['tipo_discapacidad'], 'verbose_name': 'Condicion Economica por discapacidad', 'verbose_name_plural': 'Condicion Economica por discapacidad'},
        ),
        migrations.AlterModelOptions(
            name='discapacitadoporgenero',
            options={'ordering': ['genero'], 'verbose_name': 'Discapacitado Por Genero', 'verbose_name_plural': 'Discapacitado Por Genero'},
        ),
        migrations.AlterModelOptions(
            name='informaciongrafica',
            options={'ordering': ['titulo'], 'verbose_name': 'Informacion gráfica', 'verbose_name_plural': 'Información gráfica'},
        ),
        migrations.AlterModelOptions(
            name='participacionpordiscapacidad',
            options={'ordering': ['tipo_discapacidad'], 'verbose_name': 'Participacion Por Discapacidad', 'verbose_name_plural': 'Participacion Por Discapacidad'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['titulo_publicacion'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='resumen',
            options={'ordering': ['sintesis'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumenes'},
        ),
        migrations.AlterModelOptions(
            name='tablas',
            options={'ordering': ['tipo'], 'verbose_name': 'Tabla', 'verbose_name_plural': 'Tablas'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='estado_autor',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado_categoria',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
    ]
