# Generated by Django 3.1 on 2023-06-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscapacitados', '0005_auto_20230602_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informaciongrafica',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
