# Generated by Django 3.1 on 2023-06-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscapacitados', '0006_auto_20230602_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
