# Generated by Django 3.1 on 2023-06-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscapacitados', '0007_auto_20230602_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='publicaciones/'),
        ),
        migrations.DeleteModel(
            name='Resumen',
        ),
    ]
