# Generated by Django 3.1 on 2023-06-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdiscapacitados', '0008_auto_20230602_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicionactividadeconomica',
            options={'verbose_name': 'Condicion Actividad Economica', 'verbose_name_plural': 'Condicion Actividad Economica'},
        ),
        migrations.AlterModelOptions(
            name='informaciongrafica',
            options={'verbose_name': 'Informacion gráfica', 'verbose_name_plural': 'Información gráfica'},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
